jenkins:
tool:
  ant:
    defaultProperties:
      - installSource:
          installers:
            - "antFromApache"
  git:
    installations:
      - home: "git"
        name: "Default"
  gradle:
    defaultProperties:
      - installSource:
          installers:
            - "gradleInstaller"
  jdk:
    defaultProperties:
      - installSource:
          installers:
            - jdkInstaller:
                acceptLicense: false
  maven:
    defaultProperties:
      - installSource:
          installers:
            - "maven"
    installations:
      - name: "Maven3"
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.6.1"
  pipelineMaven:
    triggerDownstreamUponResultAborted: false
    triggerDownstreamUponResultFailure: false
    triggerDownstreamUponResultNotBuilt: false
    triggerDownstreamUponResultSuccess: true
    triggerDownstreamUponResultUnstable: false
jobs:
  - script: >
      pipelineJob('pipeline2355') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/mkrzyzanowski/blog-001.git' }
                        branch '*/docker-for-mac'
                        extensions {}
                    }
                  }
              }
          }
      }